version: '3.8'
services:
  feelandmatch-frontend:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    restart: unless-stopped